### ISSUE TITLE
Please consider adding a LICENSE file

### ISSUE THREAD

**Issue by michaeldo1** [erica/TypeScript-xclangspec#2]
Thanks for this plugin! I would like to incorporate it into Chromium (ccrev.com/c/3646578), but the "license" text in the readme file is not sufficient in order to allow our use of it. Could you please add a LICENSE file at the root of the project?

Of course, choosing the specific license is up to you, but based on the existing README text, [0BSD] may work for you or [ISC] which additionally includes a copyright line.

[0BSD]: https://opensource.org/licenses/0BSD
[ISC]: https://opensource.org/licenses/ISC

**Comment by michaeldo1** [comment]
Just to be transparent and provide an update: I may have a workaround by simply setting the `explicitFileType` within the Xcode project instead of requiring the installation of this Xcode Plugin. This seems to work so far and is not inconvenient as the Xcode project is already generated by a script. (crrev.com/c/3645558)

**Comment by erica** [comment]
I'm happy to add a license, but are you saying you don't need/want one anymore?

**Comment by michaeldo1** [comment]
Sorry for the back and forth here! Thank you for the response, and that's correct, I no longer need you to do anything.

After filing this issue, I looked for other workarounds and discovered that setting `explicitFileType` inside the Xcode project works for us and allows editing the .ts files the same as .js without the annoying Xcode warning about unidentified plugins.
